# Generated by Django 5.0.6 on 2024-06-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("restart_interval", models.FloatField(null=True)),
                ("sleep_interval", models.FloatField(null=True)),
            ],
            options={
                "db_table": "django_command_queue_worker",
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.IntegerField()),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="django_command_queue.worker",
                    ),
                ),
            ],
            options={
                "db_table": "django_command_queue_call_log",
            },
        ),
        migrations.CreateModel(
            name="WorkerException",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("exc_class", models.CharField(max_length=255, verbose_name="Class")),
                ("exc_message", models.TextField(verbose_name="Message")),
                ("exc_traceback", models.TextField(verbose_name="Traceback")),
                ("created_at", models.IntegerField()),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="django_command_queue.worker",
                    ),
                ),
            ],
            options={
                "db_table": "django_command_queue_worker_exception",
            },
        ),
        migrations.CreateModel(
            name="WorkerStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.FloatField()),
                ("updated_at", models.FloatField(null=True)),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="django_command_queue.worker",
                    ),
                ),
            ],
            options={
                "db_table": "django_command_queue_worker_status",
            },
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="django_command_queue.worker",
                    ),
                ),
            ],
            options={
                "db_table": "django_command_queue",
                "unique_together": {("worker", "name")},
            },
        ),
    ]
